on:
  push:
    branches:
      - 2.x

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: php
          target-branch: ${{ github.ref_name }}
